name: LEONARDO PASSERI
favicon: null
layout_spectrum: 0.24914
typography_spectrum: 0.50035
title: LEONARDO PASSERI - Contemporary Artist -
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcbcbc'
    - '#000000'
    - '#858585'
    - '#3a3a3a'
    - '#f2f2f2'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
